### PR TITLE
LRDOCS-4704 portlet provider

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Eudaldo!

I hope you're doing well. For 7.1, I updated and rewrote parts of the PortletProvider tutorial. 

Can you review the tutorial?

https://issues.liferay.com/browse/LRDOCS-4704

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi @ealonso ,
When might you be able to review this Portlet Providers tutorial? thanks

**Comment by ealonso** [comment]
Hey @jhinkey,

Yesterday was my first day after holidays and I have a lot of things in my queue, I'm going to try to review it this week.

Regards,
Eudaldo.

**Comment by jhinkey** [comment]
… in that case, welcome back, Eudaldo! :-)

No rush. Thanks. Jim

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Hi @jhinkey,

I've just sent you a PR with two micro changes. https://github.com/jhinkey/liferay-docs/pull/421

Thanks!

**Comment by jhinkey** [comment]
Hi @pavel-savinov !

That's great! Thanks you!!

**Pull request closed without merging**
